[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
gas_reports = ["NFTMarket"]

# Anvil local network configuration
[rpc_endpoints]
anvil = "http://127.0.0.1:8545"

[etherscan]
anvil = { key = "dummy", url = "http://127.0.0.1:8545" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
